Hi
Code4Community/git-tutorial pull request #43
Opened 2021-08-30 23:45 UTC by Tuhin-Patel

No issues had

2021-08-30 23:47 UTC, avascherocman approved these changes
Your pr name should summarize your changes :)

2021-08-31 00:09 UTC, arizeltser reviewed
Looks like you put your section inside of another section instead of below it. Make sure "</div>" of the previous person is above your first line

2021-08-31 00:59 UTC, adambricelis requested changes

2021-08-31 00:59 UTC, adambricelis commented on index.html
> +          <p>Tuhin Patel</p>
Please do not delete Max's head. Try adding your code to the end of the file :)

2021-09-19 16:11 UTC, adambricelis commented
Please switch to the master branch, pull the latest changes, create another branch, redo your changes, and submit another PR.

2021-09-19 16:11 UTC, closed without merging